#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

#Colores del borde
bspc config normal_border_color "#04a5e5"
bspc config focused_border_color "#ea76cb"
bspc config urgent_border_color "#d20f39"
bspc config presel_border_color "#40a02b"
bspc config normal_frame_opacity 0.80
bspc config focused_frame_opacity 1
##########################################

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

picom &
~/.fehbg &
~/.config/polybar/launch.sh
